apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - netpol-hbone.yaml
  - nodelocal-dns.yaml

patches:
  - target:
      kind: Namespace
      name: apps
    patch: |-
      - op: add
        path: /metadata/labels/istio.io~1dataplane-mode
        value: ambient
      - op: add
        path: /metadata/labels/istio.io~1use-waypoint
        value: waypoint
